spring.application.name=demo
server.port=8091
server.error.include-message=always
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username="Carlos"
spring.datasource.password="123"
spring.datasource.url="jdbc:mariadb://localhost:3306/concesionario"